# This file contains all the data for the passes. I made it into a file so I didn't have to raw declare them in code. This looks better IMHO.
# If the width and height are 0, they will inherit the screen size.
# TODO: Add samplers? Move all frame resources to this lil file?
# TODO: Move pipeline creation to a toml file as well?

#############################
# GBuffer
[GBufferDepth]
Type = "Texture"
Width = 0
Height = 0
Format = "D32"
Usage = "Depth"

[GBufferNormal]
Type = "Texture"
Width = 0
Height = 0
Format = "RGB11"
Usage = "Render"

[GBufferAlbedo]
Type = "Texture"
Width = 0
Height = 0
Format = "RGBA8"
Usage = "Render"
#############################

#############################
# Composite
[OutputLDR]
Type = "Texture"
Width = 0
Height = 0
Format = "RGBA8"
Usage = "Render"
#############################

#############################
# Forward
[CameraRingBuffer]
Type = "RingBuffer"
Size = 512

[MainColorBuffer]
Type = "Texture"
Width = 0
Height = 0
Format = "RGBA16"
Usage = "Render"
#############################

#############################
# CSM
[CascadeRingBuffer]
Type = "RingBuffer"
Size = 1024

[ShadowCascade0]
Type = "Texture"
Width = 2048
Height = 2048
Format = "D32"
Usage = "Depth"

[ShadowCascade1]
Type = "Texture"
Width = 2048
Height = 2048
Format = "D32"
Usage = "Depth"

[ShadowCascade2]
Type = "Texture"
Width = 2048
Height = 2048
Format = "D32"
Usage = "Depth"

[ShadowCascade3]
Type = "Texture"
Width = 2048
Height = 2048
Format = "D32"
Usage = "Depth"
#############################

#############################
# Bokeh Depth of Field
[NearPlaneCOC]
Type = "Texture"
Width = 0
Height = 0
Format = "RGBA16"
Usage = "Render"

[FarPlaneCOC]
Type = "Texture"
Width = 0
Height = 0
Format = "RGBA16"
Usage = "Render"
